### ISSUE TITLE
Fails to parse IIXDR

### ISSUE THREAD

**Issue by Piorosen** [adrianmo/go-nmea#109]
occur error when parsing data.
i received error message, "nmea: IIXDR invalid transducer type:  A"

my gps data sender is providing bellow data
```$IIXDR, A, 0.0, D, ROLL, A, 0.0, D, PITCH*15```

**Comment by aldas** [comment]
every field has really leading space?

**Comment by Piorosen** [comment]
yes, because nmea data is provided by simulator.

**Comment by aldas** [comment]
At the moment library does not try to actively trim fields from whitespaces as leading space is not something "normal". For example leading zero(s) `0` is valid thing for numbers by NMEA0183 spec but space?

`$IIXDR, A, 0.0, D, ROLL, A, 0.0, D, PITCH*15` has 8 extra spaces. Considering 9600 baudrate being common this is quite huge overhead. Each extra character at these low transfer speeds is very expensive for throughput.

I guess we could ignore leading spaces for some of the field types - number, enums but for `string` fields this leads to question - could be that leading space is intended or is it not?

**Comment by Piorosen** [comment]
Thank you for letting us know what caused this.
i was able to determine the cause of the issue and resolve it. Thank you.
@aldas 

this issue is closed that solve.
