### ISSUE TITLE
"GNRMC invalid direction" error after lib update to 22095aa1b48050243d3eb9a001ca80eb91a0c6fa

### ISSUE THREAD

**Issue by amurchick** [adrianmo/go-nmea#14]
On this string:
```
$GNRMC,100538.00,A,5546.27711,N,03736.91144,E,0.061,,260318,,,A*60
```
Before lib update to 22095aa1b48050243d3eb9a001ca80eb91a0c6fa - all worked.

**Comment by icholy** [comment]
I think the issue here is that `(*parser).EnumString` should allow the empty string.
