### ISSUE TITLE
nmea.ParseSentence output

### ISSUE THREAD

**Issue by adityaalviori** [adrianmo/go-nmea#18]
Hi, i am newbie on Golang and the NMEA library too. 

I have a question about the output when i use nmea.ParseSentence. 

this is the code, i changed nmea.Parse to nmea.ParseSentence

package main

import (
  "fmt"
  "github.com/adrianmo/go-nmea"
)

func main() {
  m, err := nmea.ParseSentence("$GPRMC,220516,A,5133.82,N,00042.24,W,173.8,231.8,130694,004.2,W*70")

  if err == nil {
    fmt.Printf("%+v\n", m)
  }
}

but the output still same with nmea.Parse. The output:
$GPRMC,220516,A,5133.82,N,00042.24,W,173.8,231.8,130694,004.2,W*70 
is it the right output?
I want to parse that NMEA, so i choose the ParseSentence. 

Thanks for your help

**Comment by adrianmo** [comment]
Hi @adityaalviori, first of all welcome to Golang and to the lib :)

To parse raw sentences you need to use the `Parse` function, not `ParseSentence`, which is used internally to parse sentences. What you get in return is a `Message` struct of the parsed type, in this case, `GPRMC`, that you can cast then to `GPRMC` and access all the fields. Here's an example:

```
package main

import (
	"fmt"
	"github.com/adrianmo/go-nmea"
)

func main() {
	sentence := "$GPRMC,220516,A,5133.82,N,00042.24,W,173.8,231.8,130694,004.2,W*70"
	m, err := nmea.Parse(sentence)
	if err == nil {
		s := m.(nmea.GPRMC)
		fmt.Printf("Raw sentence: %v\n", s)
		fmt.Printf("Time: %v\n", s.Time.String())
		fmt.Printf("Validity: %v\n", s.Validity)
		fmt.Printf("Latitude GPS: %v\n", s.Latitude.PrintGPS())
		fmt.Printf("Latitude DMS: %v\n", s.Latitude.PrintDMS())
		fmt.Printf("Longitude GPS: %v\n", s.Longitude.PrintGPS())
		fmt.Printf("Longitude DMS: %v\n", s.Longitude.PrintDMS())
		fmt.Printf("Speed: %v\n", s.Speed)
		fmt.Printf("Course: %v\n", s.Course)
		fmt.Printf("Date: %v\n", s.Date.String())
		fmt.Printf("Variation: %v\n", s.Variation)
	} else {
		panic(err)
	}
}
```

I'm going to close the issue, but please reopen it again if this does not solve your issue.

Regards,
-Adrian
