### ISSUE TITLE
Make `ParseSentence` function unexported

### ISSUE THREAD

**Issue by adrianmo** [adrianmo/go-nmea#21]
Judging by #18, it looks like the `ParseSentence` function is causing confusion when using the library. Making it unexported would remove this potential confusion.

In a first inspection, I didn't see any reason to export the function as it's only used internally. 

@icholy any thoughts?

**Comment by icholy** [comment]
@adrianmo yeah, that makes sense to me.

**Comment by icholy** [comment]
@adrianmo actually, I've used the `ParseSentence` function for debugging things before. What if, we rename it to `ParseFields` and rename `Sent` to `Fields` ?

**Comment by adrianmo** [comment]
@icholy even if it's unexported we can still find ways to debug it, or just exporting it temporarily.

**Comment by icholy** [comment]
@adrianmo I just pushed a branch with the `RawFields` idea. Not sure if it's a good idea.

**Comment by adrianmo** [comment]
@icholy I'm happy with the interface `Message` renamed to `Sentence` as it represents the concept better. But not with the `Sent` to `RawFields` rename. `Sent` is definitely not the best name, but `RawFields` is not really representing the struct and forces you to rename also the `Fields` field. How does `RawSentence` or `PlainSentence` or `BaseSentence` sound?

**Comment by adrianmo** [comment]
IMO, `BaseSentence` is the best candidate...

**Comment by icholy** [comment]
The only reason I wanted to change the name was so that we could rename `ParseSentence` to `ParseFields` which would make it less confusing. Here's what I think we should do:

* Unexport `ParseSentence`
* Rename `Message` to `Sentence`.

**Comment by adrianmo** [comment]
I'm going to submit a PR just to fix this issue (unexport `ParseSentence`). Then I'll submit another one with a proposal for the renaming that we can use for discussion.
