### ISSUE TITLE
Document message specification

### ISSUE THREAD

**Issue by icholy** [adrianmo/go-nmea#48]
Since there's no public canonical nmea reference, we've been linking to different resources on the web. It would be better to maintain our own copy of the message specifications that we implement.

**Comment by icholy** [comment]
@adrianmo can you enable the wiki?

**Comment by sthorshaug** [comment]
If someone creates the initial framework, I could write some of the messages if you want.

**Comment by icholy** [comment]
I don't have time to work on this.
