### ISSUE TITLE
nmea: sentence checksum mismatch [6B != 6B ]

### ISSUE THREAD

**Issue by zhh827** [adrianmo/go-nmea#57]
if checksum != strings.TrimSpace(checksumRaw) {
		return BaseSentence{}, fmt.Errorf(
			"nmea: sentence checksum mismatch [%s != %s]", checksum, checksumRaw)
	}

**Comment by icholy** [comment]
@zhh827 do you have the sentence that is causing this?

**Comment by icholy** [comment]
@adrianmo  I'm assuming this is caused by the @zhh827 using a message string with trailing whitespace.
