### ISSUE TITLE
latest version (v1.5.0)  does not include the new supported sentences 

### ISSUE THREAD

**Issue by ahmedMHasan** [adrianmo/go-nmea#91]
Even though I am using the latest version (v1.5.0) but I cant use the new added supported sentences such as alarm sentences.

**Comment by icholy** [comment]
@adrianmo will need to make a release with the new changes. It's around the holidays, so it's likely that he's taking some time off. You can do `go get github.com/adrianmo/go-nmea@master` in the meantime.

**Comment by adrianmo** [comment]
@ahmedMHasan - v1.6.0 is out now and adds support for all sentences in the README file.
